import { StyleSheet } from 'react-native';
import { Colors } from '../globals/Colors';

export const ButtonStyles = StyleSheet.create({
	bottomCenter: { 
		position: 'absolute', 
		alignSelf: 'center',
		bottom: 34,
	},
	bottomRight: { 
		position: 'absolute', 
		alignSelf: 'flex-end',
		bottom: 34,
		paddingRight: 20,
	},
	bottomLeft: { 
		position: 'absolute', 
		alignSelf: 'flex-start',
		bottom: 34,
		paddingLeft: 20,
	},
	radioButtonSmall: {
		flex: 1,
		borderColor: Colors.lightGrey,
		borderWidth: 0.5,
		borderRadius: 5,
		paddingVertical: 18,
		textAlign: 'center',
		justifyContent: 'center',
		alignItems: 'center',
		marginHorizontal: 5,
	},
	radioButtonSmallSelected: {
		flex: 1,
		borderColor: Colors.primary,
		backgroundColor: Colors.primary,
		borderWidth: 0.5,
		borderRadius: 5,
		shadowOffset: { width: 0, height: 5 },
		shadowColor:  Colors.primary,
		shadowOpacity: 0.3,
		shadowRadius: 5,
		paddingVertical: 18,
		textAlign: 'center',
		justifyContent: 'center',
		alignItems: 'center',
		marginHorizontal: 5,
	},
	radioButtonLarge: {
		flex: 1,
		borderColor: Colors.lightGrey,
		borderWidth: 0.5,
		borderRadius: 5,
		paddingVertical: 12,
		textAlign: 'center',
		justifyContent: 'center',
		alignItems: 'center',
		marginHorizontal: 5,
	},
	radioButtonLargeSelected: {
		flex: 1,
		borderColor: Colors.primary,
		backgroundColor: Colors.primary,
		borderWidth: 0.5,
		borderRadius: 5,
		shadowOffset: { width: 0, height: 5 },
		shadowColor:  Colors.primary,
		shadowOpacity: 0.3,
		shadowRadius: 5,
		paddingVertical: 12,
		textAlign: 'center',
		justifyContent: 'center',
		alignItems: 'center',
		marginHorizontal: 5,
	},
})